const API='https://pachinko-data-api.onrender.com/api/data';
const HISTORY_KEY='pachinko-tracker-v3922-history-v1';
const $=id=>document.getElementById(id);let data=[];let dataUpdated=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function status(t){$('status').textContent=t}
function fmt(n){return n==null||n===''?'—':Number(n).toLocaleString('ja-JP')}
function dayKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date())}
function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'{}')}catch{return {}}}
function saveHistory(){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{}}
let history=loadHistory();
function snapshotMachine(m){const d=m.days?.[0]||{},s=m.detailStats||{};const maxPayout=d.maxPayout??s.maxPayout,big=d.big??s.big,start=d.start??s.start,continuation=d.continuation??s.continuation,probability=d.probability??s.probability;if(maxPayout==null&&big==null&&start==null&&continuation==null&&probability==null)return null;return {day:dayKey(),maxPayout:maxPayout==null?null:Number(String(maxPayout).replace(/,/g,'')),big:big==null?null:Number(String(big).replace(/,/g,'')),start:start==null?null:Number(String(start).replace(/,/g,'')),continuation:continuation==null?null:Number(String(continuation).replace(/,/g,'')),probability:probability??null,updatedAt:new Date().toISOString()}}
function recordHistory(){for(const m of data){const snap=snapshotMachine(m);if(!snap)continue;const id=String(m.id),arr=Array.isArray(history[id])?history[id]:[],i=arr.findIndex(x=>x.day===snap.day);if(i>=0)arr[i]=snap;else arr.unshift(snap);history[id]=arr.slice(0,30)}saveHistory()}
function historyDays(m){const map=new Map();for(const d of (Array.isArray(m.days)?m.days:[]))map.set(d.day===0?dayKey():String(d.day),d);for(const d of (history[String(m.id)]||[]))if(!map.has(d.day))map.set(d.day,d);return [...map.values()].slice(0,30)}
function chartValue(d){if(d?.maxPayout!=null&&d.maxPayout!=='')return Number(String(d.maxPayout).replace(/,/g,''));if(d?.big!=null&&d.big!=='')return Number(String(d.big).replace(/,/g,''));return 0}
function dayLabel(d,i){if(d?.day===0)return '本日';if(typeof d?.day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d.day))return d.day.slice(5);return `${i+1}日前`}
function drawFallback(m,days){const c=$('chart'),ctx=c.getContext('2d'),w=c.clientWidth||320,h=320,p=48;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);const vals=days.map(chartValue),max=Math.max(...vals,1000),min=-max,innerW=w-2*p,innerH=h-2*p,n=Math.max(1,vals.length-1),zero=p+innerH/2;ctx.font='12px system-ui';ctx.fillStyle='#cbd5e1';ctx.strokeStyle='#64748b';ctx.globalAlpha=.55;for(let i=0;i<=6;i++){const y=p+i*innerH/6;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke();const v=Math.round(max-(2*max*i/6));ctx.globalAlpha=.9;ctx.fillText(fmt(v),3,y+4);ctx.globalAlpha=.55}for(let i=0;i<vals.length;i++){const x=p+i*innerW/n;ctx.beginPath();ctx.moveTo(x,p);ctx.lineTo(x,h-p);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(p,zero);ctx.lineTo(w-p,zero);ctx.stroke();ctx.strokeStyle='#9bd8e5';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{const x=p+i*innerW/n,y=zero-(v/max)*(innerH/2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#fff';ctx.lineWidth=1;vals.forEach((v,i)=>{const x=p+i*innerW/n,y=zero-(v/max)*(innerH/2);ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillText(fmt(Math.round(v)),Math.max(2,x-18),Math.max(14,y-9));ctx.fillText(dayLabel(days[i],i),Math.max(2,x-18),h-10)});$('chartInfo').textContent=`台 ${m.id} · ${days.length}日分 · P'sCUBE風フォールバック`}
function renderPcubeCharts(m,days){const box=$('chartStack');box.innerHTML='';const assets=Array.isArray(m.graphAssets)?m.graphAssets.filter(Boolean):[];if(assets.length){assets.slice(0,Math.min(days.length||7,assets.length)).forEach((u,i)=>{const wrap=document.createElement('div');wrap.className='pcubeDay';const title=document.createElement('div');title.className='pcubeDayTitle';title.textContent=i===0?'本日':`${i}日前`;const img=document.createElement('img');img.loading='lazy';img.src=u;img.alt=`台 ${m.id} ${title.textContent} P'sCUBE グラフ`;img.onerror=()=>wrap.remove();wrap.append(title,img);box.append(wrap)});$('chart').style.display='none';$('chartInfo').textContent=`台 ${m.id} · P'sCUBEの実グラフ ${assets.length}件`;}else{$('chart').style.display='block';drawFallback(m,days);}}
function draw(m){if(!m)return;const days=historyDays(m).slice(0,Number($('range').value)||7);if(!days.length){$('chartStack').innerHTML='<div class="empty">日別データがありません。</div>';$('chart').style.display='none';return}renderPcubeCharts(m,days);const d=days[0]||{},ls=m.detailStats||{};$('detail').innerHTML=`<div class="detailGrid"><div><span>本日大当り</span><b>${d.big??ls.big??'—'}</b></div><div><span>継続回数</span><b>${d.continuation??ls.continuation??'—'}</b></div><div><span>最大継続</span><b>${d.maxContinuation??ls.maxContinuation??'—'}</b></div><div><span>大当り確率</span><b>${esc(d.probability||ls.probability||'—')}</b></div><div><span>累計スタート</span><b>${d.start??ls.start??'—'}</b></div><div><span>最大放出</span><b>${d.maxPayout!=null?fmt(d.maxPayout):(ls.maxPayout!=null?fmt(ls.maxPayout):'—')} pt</b></div></div>`;$('hits').innerHTML=(m.todayHits||[]).map(h=>`<tr><td>${h.no}</td><td>${esc(h.time)}</td><td>${h.start??'—'}</td><td>${h.payout==null?'↑':fmt(h.payout)}</td><td>${esc(h.status)}</td></tr>`).join('')||'<tr><td colspan="5">履歴なし</td></tr>';renderGraphAssets(m)}
function renderGraphAssets(m){const box=$('graphAssets');const assets=Array.isArray(m.graphAssets)?m.graphAssets.filter(Boolean):[];box.innerHTML=assets.map((u,i)=>`<div class="assetWrap"><span>グラフ ${i+1}</span><img loading="lazy" src="${esc(u)}" alt="P'sCUBE graph ${esc(m.id)}" onerror="this.parentElement.remove()"></div>`).join('')||'<div class="empty">P\'sCUBEからグラフ画像を取得できていません。</div>'}
function render(){$('machineCount').textContent=data.length;$('trendCount').textContent=data.filter(x=>historyDays(x).length>1).length;$('updatedAt').textContent=dataUpdated?new Date(dataUpdated).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'—';$('machineSelect').innerHTML=data.map(x=>`<option value="${esc(x.id)}">${esc(x.id)} · ${esc(x.model||'')}</option>`).join('');$('analysis').innerHTML=data.map(x=>{const d=historyDays(x)[0]||{};return `<div class="machine"><div><b>台 ${esc(x.id)}</b><small>${esc(x.model||'')}</small></div><div class="machineMetric">本日 ${d.big??'—'}回<br><span>最大 ${d.maxPayout!=null?fmt(d.maxPayout):'—'} pt</span></div><button class="delete" onclick="pick('${esc(x.id)}')">見る</button></div>`}).join('')||'<div class="empty">データなし</div>';if(data.length)draw(data[0])}
window.pick=id=>{const m=data.find(x=>x.id===id);if(m){$('machineSelect').value=id;draw(m)}};
$('machineSelect').onchange=e=>draw(data.find(x=>x.id===e.target.value));$('range').onchange=()=>draw(data.find(x=>x.id===$('machineSelect').value));$('refreshBtn').onclick=load;
async function load(){status("P'sCUBEからデータ取得中…");try{const r=await fetch(API+'?t='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'データ取得エラー');data=j.machines;dataUpdated=j.updated;recordHistory();status(j.liveOk?`P'sCUBE接続済み · ${new Date(j.updated).toLocaleString('ja-JP')}`:'基準データ表示');render()}catch(e){status('取得エラー: '+e.message)}}
load();setInterval(load,600000);