const API='https://pachinko-data-api.onrender.com/api/data';
const HISTORY_KEY='pachinko-tracker-v3923-history-v1';
const $=id=>document.getElementById(id);
let data=[],dataUpdated=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=n=>n==null||n===''?'—':Number(n).toLocaleString('ja-JP');
const dayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date());
const status=t=>{$('status').textContent=t};
let history=(()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'{}')}catch{return {}}})();
function saveHistory(){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{}}
function snapshot(m){const d=m.days?.[0]||{},s=m.detailStats||{};const fields=['maxPayout','big','start','continuation','probability'];if(fields.every(k=>d[k]==null&&s[k]==null))return null;return {day:dayKey(),maxPayout:d.maxPayout??s.maxPayout??null,big:d.big??s.big??null,start:d.start??s.start??null,continuation:d.continuation??s.continuation??null,probability:d.probability??s.probability??null,updatedAt:new Date().toISOString()}}
function recordHistory(){for(const m of data){const s=snapshot(m);if(!s)continue;const id=String(m.id),a=Array.isArray(history[id])?history[id]:[],i=a.findIndex(x=>x.day===s.day);if(i>=0)a[i]=s;else a.unshift(s);history[id]=a.slice(0,30)}saveHistory()}
function daysFor(m){const map=new Map();for(const d of Array.isArray(m.days)?m.days:[])map.set(d.day===0?dayKey():String(d.day),d);for(const d of history[String(m.id)]||[])if(!map.has(d.day))map.set(d.day,d);return [...map.values()].slice(0,30)}
function chartSource(days){const hasP=days.some(d=>d?.maxPayout!=null&&d.maxPayout!=='');return {field:hasP?'maxPayout':'big',label:hasP?'最大放出数 (pt)':'大当り回数 (回)'}}
function drawPcube(m,days){const box=$('chartStack');box.innerHTML='';$('chart').style.display='none';const src=chartSource(days);const wrap=document.createElement('div');wrap.className='pcubeDay';const title=document.createElement('div');title.className='pcubeDayTitle';title.textContent=`台 ${m.id} · ${days.length}日分`;
const canvas=document.createElement('canvas');canvas.className='pcubeCanvas';canvas.height=340;wrap.append(title,canvas);box.append(wrap);const ctx=canvas.getContext('2d');const dpr=devicePixelRatio||1,w=Math.max(300,box.clientWidth||340),h=340,p={l:58,r:16,t:28,b:42};canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width='100%';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#222';ctx.fillRect(0,0,w,h);const vals=days.slice(0,30).map(d=>Number(String(d?.[src.field]??0).replace(/,/g,''))||0).reverse();const max=Math.max(...vals,src.field==='maxPayout'?5000:10);const min=src.field==='maxPayout'?-max/2:-Math.max(1,max*.25);const innerW=w-p.l-p.r,innerH=h-p.t-p.b;const y=v=>p.t+(max-v)/(max-min)*innerH;const x=i=>p.l+(vals.length<=1?innerW/2:i*innerW/(vals.length-1));ctx.font='12px system-ui';ctx.textAlign='right';ctx.lineWidth=1;ctx.setLineDash([5,5]);ctx.strokeStyle='#777';ctx.fillStyle='#ddd';for(let i=0;i<=6;i++){const yy=p.t+i*innerH/6;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();const v=max-(max-min)*i/6;ctx.fillText(Math.round(v).toLocaleString('ja-JP'),p.l-8,yy+4)}ctx.textAlign='center';for(let i=0;i<vals.length;i++){const xx=x(i);ctx.beginPath();ctx.moveTo(xx,p.t);ctx.lineTo(xx,h-p.b);ctx.stroke();if(vals.length<=10)ctx.fillText(i===vals.length-1?'本日':`${vals.length-1-i}日前`,xx,h-15)}ctx.setLineDash([]);const zy=Math.max(p.t,Math.min(h-p.b,y(0)));ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.l,zy);ctx.lineTo(w-p.r,zy);ctx.stroke();if(vals.length){ctx.strokeStyle='#9bd8e5';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();ctx.fillStyle='#fff';ctx.font='11px system-ui';vals.forEach((v,i)=>{ctx.beginPath();ctx.arc(x(i),y(v),4,0,Math.PI*2);ctx.fill();ctx.fillText(fmt(Math.round(v)),x(i),Math.max(14,y(v)-9))})}const note=document.createElement('div');note.className='chartNote';note.textContent=`Nguồn biểu đồ dự phòng: ${src.label}. Khi P'sCUBE cung cấp ảnh biểu đồ gốc, ứng dụng sẽ ưu tiên ảnh gốc.`;wrap.append(note);$('chartInfo').textContent=`台 ${m.id} · ${days.length} ngày · ${src.label}`}
function draw(m){if(!m)return;const days=daysFor(m).slice(0,Number($('range').value)||7);if(!days.length){$('chartStack').innerHTML='<div class="empty">Chưa có dữ liệu biểu đồ cho máy này.</div>';$('chartInfo').textContent='';return}drawPcube(m,days);const d=days[0]||{},s=m.detailStats||{};$('detail').innerHTML=`<div class="detailGrid"><div><span>本日大当り</span><b>${d.big??s.big??'—'}</b></div><div><span>継続回数</span><b>${d.continuation??s.continuation??'—'}</b></div><div><span>最大継続</span><b>${d.maxContinuation??s.maxContinuation??'—'}</b></div><div><span>大当り確率</span><b>${esc(d.probability??s.probability??'—')}</b></div><div><span>累計スタート</span><b>${d.start??s.start??'—'}</b></div><div><span>最大放出</span><b>${d.maxPayout!=null?fmt(d.maxPayout):(s.maxPayout!=null?fmt(s.maxPayout):'—')} pt</b></div></div>`;const assets=Array.isArray(m.graphAssets)?m.graphAssets.filter(Boolean):[];$('graphAssets').innerHTML=assets.map((u,i)=>`<div class="assetWrap"><span>グラフ ${i+1}</span><img loading="lazy" src="${esc(u)}" alt="P'sCUBE graph ${esc(m.id)}" onerror="this.parentElement.remove()"></div>`).join('')||'<div class="empty">Máy này chưa có ảnh biểu đồ gốc từ P\'sCUBE; đang hiển thị biểu đồ dữ liệu ngày.</div>';}
function render(){ $('machineCount').textContent=data.length;$('trendCount').textContent=data.filter(m=>daysFor(m).length>1).length;$('updatedAt').textContent=dataUpdated?new Date(dataUpdated).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'—';$('machineSelect').innerHTML=data.map(m=>`<option value="${esc(m.id)}">${esc(m.id)} · ${esc(m.model||'')}</option>`).join('');$('analysis').innerHTML=data.map(m=>{const d=daysFor(m)[0]||{};return `<div class="machine"><div><b>台 ${esc(m.id)}</b><small>${esc(m.model||'')}</small></div><div class="machineMetric">本日 ${d.big??'—'}回<br><span>最大 ${d.maxPayout!=null?fmt(d.maxPayout):'—'} pt</span></div><button class="delete" onclick="pick('${esc(m.id)}')">見る</button></div>`}).join('')||'<div class="empty">データなし</div>';if(data.length)draw(data[0]);}
window.pick=id=>{const m=data.find(x=>String(x.id)===String(id));if(m){$('machineSelect').value=m.id;draw(m)}};
$('machineSelect').onchange=e=>draw(data.find(m=>String(m.id)===e.target.value));$('range').onchange=()=>draw(data.find(m=>String(m.id)===$('machineSelect').value));$('refreshBtn').onclick=load;
async function load(){status("P'sCUBEからデータ取得中…");try{const r=await fetch(API+'?t='+Date.now(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'データ取得エラー');data=j.machines||[];dataUpdated=j.updated;recordHistory();status(j.liveOk?`P'sCUBE接続済み · ${new Date(j.updated).toLocaleString('ja-JP')}`:'基準データ表示');render()}catch(e){status('取得エラー: '+e.message)}}
load();setInterval(load,600000);