const http=require('http'),https=require('https'),fs=require('fs');
const HOST='https://www.pscube.jp',MODEL='e牙狼12 XX-MJ',VERSION='3.9.31';
const PATHS=['/dedamajyoho-P-townDMMpachi/c732920/cgi-bin/nc-v03-001.php?cd_ps=1&bai=0.89',`/dedamajyoho-P-townDMMpachi/c732920/cgi-bin/nc-v05-003.php?cd_ps=1&bai=0.89&nmk_kisyu=${encodeURIComponent(MODEL)}`];
const DIRECTS=PATHS.flatMap(p=>[HOST+p,'https://pscube.jp'+p]);
const GOOGLE=PATHS.map(p=>'https://www-pscube-jp.translate.goog'+p+'&_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en');
const JINA=PATHS.map(p=>'https://r.jina.ai/https://www.pscube.jp'+p);
const PROXIES=[u=>'https://corsproxy.io/?url='+encodeURIComponent(u),u=>'https://api.allorigins.win/raw?url='+encodeURIComponent(u)];
const READERS=[...DIRECTS,...GOOGLE,...JINA,...DIRECTS.flatMap(u=>PROXIES.map(p=>p(u)))];
const MOBILE_FILE=__dirname+'/data/mobile-live.json';
function loadMobile(){try{return JSON.parse(fs.readFileSync(MOBILE_FILE,'utf8'))}catch{return {updated:null,url:null,machines:[]}}}
let mobileState=loadMobile();
function saveMobile(){try{fs.mkdirSync(__dirname+'/data',{recursive:true});fs.writeFileSync(MOBILE_FILE,JSON.stringify(mobileState,null,2))}catch(e){console.error('mobile save',e.message)}}
function fetchText(url,timeout=10000,depth=0){return new Promise((resolve,reject)=>{if(depth>6)return reject(Error('Too many redirects'));let target;try{target=new URL(url)}catch(e){return reject(e)}const mod=target.protocol==='http:'?http:https;const req=mod.get(target,{headers:{'User-Agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36','Accept':'text/html,application/xhtml+xml,text/plain,*/*','Accept-Language':'ja-JP,ja;q=0.9,en;q=0.8','Referer':'https://www.pscube.jp/','Connection':'close'},timeout},r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location){r.resume();return fetchText(new URL(r.headers.location,target).href,timeout,depth+1).then(resolve).catch(reject)}let b='';r.setEncoding('utf8');r.on('data',x=>b+=x);r.on('end',()=>r.statusCode>=200&&r.statusCode<300?resolve({html:b,url:target.href,status:r.statusCode}):reject(Error('HTTP '+r.statusCode)));r.on('error',reject)});req.on('timeout',()=>req.destroy(Error('Timeout')));req.on('error',reject)})}
function clean(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCharCode(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCharCode(Number(x))).replace(/\s+/g,' ').trim()}
function nums(s){return (String(s||'').match(/[-+]?\d[\d,]*(?:\.\d+)?/g)||[]).map(x=>Number(x.replace(/,/g,''))).filter(Number.isFinite)}
function abs(base,u){try{return new URL(u,base).href}catch{return null}}
function graphAssets(html,base){const out=[];const add=u=>{u=abs(base,u);if(u&&/(graph|slump|chart|data|history|graphical|detail)/i.test(u))out.push(u)};let m;const re=/(?:<img|<source|<a|<link)[^>]+(?:src|data-src|href|srcset)=["']([^"']+)["'][^>]*>/gi;while((m=re.exec(html||'')))m[1].split(',').forEach(x=>add(x.trim().split(' ')[0]));const are=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;while((m=are.exec(html||''))){const label=clean(m[2]);if(/詳細グラフ|グラフ|履歴/i.test(label))add(m[1])}return [...new Set(out)].slice(0,80)}
function extractMachineIds(t){const ids=new Set();let m;for(const re of[/\b(\d{3,4})\b/g,/台\s*(?:番|番号)?\s*[:：]?\s*(\d{3,4})/g]){while((m=re.exec(t||''))){const id=m[1]||m[2];if(Number(id)>=1&&Number(id)<=9999)ids.add(id.padStart(4,'0'))}}return [...ids]}
function detailLinks(html,base,id){const out=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html||''))){const u=abs(base,m[1]),t=clean(m[2]);if(u&&((t.includes(id))||u.includes(id)))out.push(u)}return [...new Set(out)].slice(0,12)}
function rowDays(raw,id){const text=clean(raw);const ns=nums(text);const pos=ns.findIndex(n=>String(Math.trunc(n)).padStart(4,'0')===id||String(Math.trunc(n))===String(Number(id)));const vals=pos>=0?ns.slice(pos+1):ns;const days=[];for(let i=0;i<Math.min(30,vals.length);i++)days.push({day:i,big:vals[i]});return days}
function parseList(html,base){const out=[],seen=new Set(),rows=[];let m;const rowRe=/<tr[\s\S]*?<\/tr>/gi;while((m=rowRe.exec(html||'')))rows.push(m[0]);if(!rows.length){const blockRe=/(?:\d{3,4})[\s\S]{0,1400}/g;while((m=blockRe.exec(html||'')))rows.push(m[0])}for(const raw of rows){const t=clean(raw);for(const id of extractMachineIds(t)){if(seen.has(id))continue;out.push({id,model:MODEL,raw:t,numbers:nums(t).slice(0,40),days:rowDays(raw,id),detailUrls:detailLinks(raw,base,id),graphAssets:graphAssets(raw,base)});seen.add(id)}}return out}
function parseDetail(html,base,m){const assets=graphAssets(html,base),text=clean(html),stats={};for(const [k,label] of[['big','大当り回数'],['continuation','継続回数'],['maxContinuation','最大継続'],['probability','大当り確率'],['start','累計スタート'],['lastStart','最終スタート'],['maxPayout','最大放出数']]){const x=text.match(new RegExp(label+'\\s*([0-9,./]+)'));if(x)stats[k]=x[1].replace(/,/g,'')}return {detailUrl:base,detailStats:stats,graphAssets:[...new Set([...(m.graphAssets||[]),...assets].filter(Boolean))].slice(0,80)}}
function loadSeed(){try{return JSON.parse(fs.readFileSync(__dirname+'/data/seed.json','utf8'))}catch{return {}}}
function loadHistory(){try{return JSON.parse(fs.readFileSync(__dirname+'/data/live-history.json','utf8'))}catch{return {updated:null,snapshots:[]}}}
function merge(seed,live){const result={};for(const id of Object.keys(seed||{}))result[id]=JSON.parse(JSON.stringify(seed[id]));for(const m of live||[])result[m.id]=Object.assign(result[m.id]||{id:m.id,model:MODEL,days:[]},{live:m,liveUpdated:new Date().toISOString(),days:m.days||[],detailUrl:m.detailUrl||null,detailStats:m.detailStats||{},graphAssets:m.graphAssets||[],numbers:m.numbers||[],raw:m.raw||null});return Object.values(result)}
function applyHistory(machines){const h=loadHistory().snapshots||[];const by={};for(const s of h){const id=String(s.id);(by[id]||(by[id]=[])).push(s)}return machines.map(m=>Object.assign(m,{history:(by[String(m.id)]||[]).slice(-10080)}))}
async function enrich(m){for(const u of(m.detailUrls||[])){try{const r=await fetchText(u,7000);return Object.assign(m,parseDetail(r.html,r.url,m))}catch{}}return m}
async function tryReader(u){const r=await fetchText(u,9000);const machines=parseList(r.html,r.url);if(!machines.length)throw Error('no machine rows found');return {url:r.url,machines:await Promise.all(machines.map(enrich))}}
async function getLive(){const settled=await Promise.allSettled(READERS.map(tryReader));const ok=settled.filter(x=>x.status==='fulfilled'&&x.value.machines?.length);if(ok.length){ok.sort((a,b)=>b.value.machines.length-a.value.machines.length);return ok[0].value}throw Error("P'sCUBE source unavailable")}
function body(req,limit=2e6){return new Promise((resolve,reject)=>{let s='',n=0;req.on('data',c=>{n+=c.length;if(n>limit){reject(Error('body too large'));req.destroy();return}s+=c});req.on('end',()=>resolve(s));req.on('error',reject)})}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}
const path=new URL(req.url,'http://localhost').pathname;try{
if(path==='/health'){res.end(JSON.stringify({ok:true,version:VERSION,source:"P'sCUBE",mobileCollector:!!mobileState.updated}));return}
if(path==='/api/mobile-import'&&req.method==='POST'){const raw=await body(req);const p=JSON.parse(raw);if(!Array.isArray(p.machines)||!p.machines.length)throw Error('machines required');mobileState={updated:p.updated||new Date().toISOString(),url:p.url||"P'sCUBE mobile WebView",machines:p.machines.slice(0,100)};saveMobile();res.end(JSON.stringify({ok:true,version:VERSION,received:mobileState.machines.length,updated:mobileState.updated}));return}
if(path==='/api/history'){const h=loadHistory();res.end(JSON.stringify({ok:true,updated:h.updated||null,snapshots:h.snapshots||[]}));return}
if(path==='/api/data'){const seed=loadSeed();let live={url:null,machines:[],error:null};if(mobileState.updated&&mobileState.machines.length){live={url:mobileState.url,machines:mobileState.machines,error:null}}else{try{live=await getLive()}catch(e){live.error=e.message}}let machines=merge(seed,live.machines);machines=applyHistory(machines);res.end(JSON.stringify({ok:true,version:VERSION,source:live.url||"P'sCUBE",liveOk:!!live.url,model:MODEL,updated:mobileState.updated||new Date().toISOString(),machines,error:live.error||null,historyUpdated:loadHistory().updated||null,mobileCollector:!!mobileState.updated}));return}
res.statusCode=404;res.end(JSON.stringify({error:'not found'}))}catch(e){res.statusCode=400;res.end(JSON.stringify({ok:false,version:VERSION,error:e.message}))}});server.listen(process.env.PORT||10000,'0.0.0.0');