const http=require('http'),https=require('https');
const HOST='https://www.pscube.jp';
const PATH='/dedamajyoho-P-townDMMpachi/c732920/cgi-bin/nc-v05-003.php?cd_ps=1&bai=0.89&nmk_kisyu=e%25E7%2589%2599%25E7%258B%25BC12%2BXX-MJ';
const DIRECTS=[HOST+PATH,'https://pscube.jp'+PATH];
// P'sCUBE may reject datacenter IPs. Jina Reader can fetch the same public HTML,
// but the target query string must stay inside the reader path instead of becoming
// Jina's own query string.
function jina(target){
  return 'https://r.jina.ai/'+target.replace(/\?/g,'%3F').replace(/&/g,'%26').replace(/=/g,'%3D');
}
const READERS=[jina('https://www.pscube.jp'+PATH),jina('https://pscube.jp'+PATH),jina('http://www.pscube.jp'+PATH)];
function fetchText(url,depth=0){return new Promise((resolve,reject)=>{if(depth>6)return reject(Error('Too many redirects'));let target;try{target=new URL(url)}catch(e){return reject(e)}const mod=target.protocol==='http:'?http:https;const req=mod.get(target,{headers:{'User-Agent':'Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 Chrome/120 Safari/537.36','Accept':'text/html,application/xhtml+xml,text/plain,*/*','Accept-Language':'ja,en;q=0.8','Connection':'close'},timeout:20000},r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location){r.resume();return fetchText(new URL(r.headers.location,target).href,depth+1).then(resolve).catch(reject)}let b='';r.setEncoding('utf8');r.on('data',x=>b+=x);r.on('end',()=>r.statusCode>=200&&r.statusCode<300?resolve({html:b,url:target.href,status:r.statusCode}):reject(Error('HTTP '+r.statusCode+' '+target.href)));r.on('error',reject)});req.on('timeout',()=>req.destroy(Error('Timeout '+target.href)));req.on('error',reject)})}
function clean(s){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCharCode(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCharCode(Number(x))).replace(/\s+/g,' ').trim()}
function nums(s){return (s.match(/[-+]?\d[\d,]*(?:\.\d+)?/g)||[]).map(x=>Number(x.replace(/,/g,''))).filter(Number.isFinite)}
function parse(html){const rows=[];const re=/<tr[\s\S]*?<\/tr>/gi;let m;while((m=re.exec(html))){const t=clean(m[0]);const id=(t.match(/\b\d{4}\b/)||[])[0];if(!id)continue;const values=nums(t);if(values.length)rows.push({id,values:values.slice(-20)})}if(rows.length)return dedupe(rows);for(const line of html.split(/\r?\n/)){const t=clean(line);const id=(t.match(/\b\d{4}\b/)||[])[0];if(!id)continue;const values=nums(t);if(values.length)rows.push({id,values:values.slice(-20)})}return dedupe(rows)}
function dedupe(rows){const seen=new Set();return rows.filter(x=>!seen.has(x.id)&&seen.add(x.id))}
async function getSource(){let last='';for(const u of [...DIRECTS,...READERS]){try{const r=await fetchText(u);if(/\b\d{4}\b/.test(r.html))return r;last='No machine numbers in '+u}catch(e){last=e.message}}throw Error(last||"P'sCUBE source unavailable")}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');const path=new URL(req.url,'http://localhost').pathname;try{if(path==='/health'){res.end(JSON.stringify({ok:true,version:'3.9.10',source:"P'sCUBE nc-v05-003",proxy:'direct+jina'}));return}if(path==='/api/data'){const src=await getSource();const machines=parse(src.html);if(!machines.length)throw Error("P'sCUBE opened but no machine rows were found");res.end(JSON.stringify({ok:true,version:'3.9.10',source:src.url,model:'e牙狼12 XX-MJ',updated:new Date().toISOString(),machines}));return}res.statusCode=404;res.end(JSON.stringify({error:'not found'}))}catch(e){res.statusCode=502;res.end(JSON.stringify({ok:false,version:'3.9.10',error:e.message,source:PATH}))}});server.listen(process.env.PORT||10000,'0.0.0.0');