package jp.pachinko.collector;

import android.app.*;import android.os.*;import android.webkit.*;import android.widget.*;import android.view.*;import java.io.*;import java.net.*;

public class MainActivity extends Activity {
 WebView w; TextView status; Handler h=new Handler(); final String PAGE="https://www.pscube.jp/dedamajyoho-P-townDMMpachi/c732920/cgi-bin/nc-v03-001.php?cd_ps=1&bai=0.89"; final String API="https://pachinko-data-api.onrender.com/api/mobile-import";
 @Override public void onCreate(Bundle b){super.onCreate(b); LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);status=new TextView(this);status.setPadding(16,16,16,16);Button now=new Button(this);now.setText("今すぐ収集");now.setOnClickListener(v->collect());l.addView(status);l.addView(now,new LinearLayout.LayoutParams(-1,-2));w=new WebView(this);w.getSettings().setJavaScriptEnabled(true);w.getSettings().setDomStorageEnabled(true);w.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){status.setText("P'sCUBE 読み込み完了。5分ごとに収集します");collect();}});l.addView(w,new LinearLayout.LayoutParams(-1,0,1));setContentView(l);w.loadUrl(PAGE);h.postDelayed(new Runnable(){public void run(){w.reload();h.postDelayed(this,300000);}},300000);}
 void collect(){w.evaluateJavascript("(function(){return JSON.stringify({url:location.href,updated:new Date().toISOString(),text:document.body.innerText,graphs:Array.from(document.images).map(x=>x.src).filter(Boolean)})})()",s->{String raw=s; new Thread(()->{try{URL u=new URL(API);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);OutputStream o=c.getOutputStream();o.write(("{\"source\":\"Android WebView\",\"payload\":"+raw+"}").getBytes("UTF-8"));o.close();int code=c.getResponseCode();runOnUiThread(()->status.setText("収集送信完了 HTTP "+code));}catch(Exception e){runOnUiThread(()->status.setText("送信エラー: "+e.getMessage()));}}).start();});}
}
